# tasks file for nat-stack-init

- name: Get the bucketname
  shell: head -1 /var/tmp/bucketname.conf | awk -F. '{print $1}'
  register: bucket_name

- name: Get the security group ID
  shell: head -1 /var/tmp/securityGroup.conf
  register: security_group

- name: Get the admin port
  shell: head -1 /var/tmp/admin_port.conf
  register: admin_port
