---
# Configure HAProxy

- name: Debug ELB DNS Name
  debug: msg="{{ target_dns.results[0].stdout_lines[0] }}"
  when:
  - debug
  tags:
  - haproxy_config
  - elbs_ips

- name: Resolve ELB DNS name A records
  shell: dig "{{ target_dns.results[0].stdout_lines[0] }}" |
         grep IN |
         grep A |
         grep -v SOA |
         egrep '(elb|eucalyptus)' |
         grep -v \; |
         awk '{print $5}' |
         sort
  register: elbs_addresses
  ignore_errors: true
  tags:
  - haproxy_config
  - elbs_ips

- name: Debug A records
  debug: msg={{ elbs_addresses.stdout }}
  when:
  - elbs_addresses|length > 7
  - elbs_addresses|success
  - debug
  tags:
  - debug
  - haproxy_config
  - elbs_ips

- name: Update the HAproxy configuration file
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  register: template_status
  when: elbs_addresses|success
  tags:
  - haproxy_config
  - elbs_ips

- name: Reload HAProxy
  service: name=haproxy state=reloaded
  when:
  - template_status|changed
  - elbs_addresses|success
  tags:
  - haproxy_config
  - elbs_ips
