---
# tasks file for nat-stack-deploy

- name: Get the latest elb.conf (destination/target)
  s3: bucket="{{ bucket_name.stdout }}"
      object="{{ who_i_am.stdout }}-{{ item  }}"
      dest="/var/tmp/{{ item }}"
      s3_url="{{ s3_url }}"
      mode=get
  with_items:
  - "target.conf"
  tags:
  - s3
  - deploy_config
