---
# configure Security Group

- name: Get opened ports
  shell:  aws ec2 describe-security-groups
          --group-id sg-b0556ed3
          --endpoint-url=`head -1 /var/tmp/ec2.conf`
          --region=eucalyptus --output=text |
          grep IPPERMISSION |
          egrep -v '(icmp|{{ admin_port.stdout }})' |
          awk '{print $2}'
  register: opened_ports

- name: Debug opened ports
  debug: msg="{{ opened_ports.stdout_lines }}"
  when:
  - debug

- name: Open SG for all src ports
  shell: aws ec2 authorize-security-group-ingress
         --protocol tcp
         --port {{ item }}
         --group-id `head -1 /var/tmp/securityGroup.conf`
         --cidr=0.0.0.0/0
         --endpoint-url=`head -1 /var/tmp/ec2.conf`
         --region=eucalyptus
         --output=text
  with_items:
  - "{{ src_port.results[0].stdout_lines }}"
  when:
  - "{{ item not in opened_ports.stdout_lines }}"

- name: Close non wanted ports
  shell: aws ec2 revoke-security-group-ingress
         --protocol tcp --port {{ item }}
         --group-id `head -1 /var/tmp/securityGroup.conf`
         --cidr=0.0.0.0/0
         --endpoint-url=`head -1 /var/tmp/ec2.conf`
         --region=eucalyptus
         --output=text
  with_items:
  - "{{ opened_ports.stdout_lines }}"
  when:
  - "{{ item not in src_port.results[0].stdout_lines }}"
  - not {{ item }} == "{{ admin_port.stdout }}"
