---
# tasks file for nat-stack-deploy

- name: pre-requesites
  include: pre_requesites.yml

- name: Set machine facts
  setup:

- name: Set EC2 facts
  action: ec2_facts
  register: ec2_data

- name: Common
  include: common.yml

- name: Update configuration from S3 files
  include: configure_from_s3.yml

- name: Parse target
  include: parse_target.yml

- name: Add crontab
  cron: name=auto-update-elb month=* day=* hour=*  minute=*/1 job="bash /etc/ansible/roles/nat-stack-deploy/files/cronjob_deploy.sh"
  when:
  - add_cron

- name: Configure Security Group
  include: configure_sg.yml

- name: Configure EIP
  include: configure_eip.yml

- name: Configure HAProxy
  include: configure_haproxy.yml
